openapi: 3.0.0
info:
  title: User Model
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        createdAt:
          type: string
          format: date-time
