apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: tradealert
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
  TRACING_ENABLED: "true"
  PROMETHEUS_ENDPOINT: "http://prometheus:9090"
