apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tradealert-rolebinding
  namespace: tradealert
subjects:
  - kind: ServiceAccount
    name: tradealert-sa
    namespace: tradealert
roleRef:
  kind: Role
  name: tradealert-role
  apiGroup: rbac.authorization.k8s.io
