apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: tradealert
type: Opaque
stringData:
  postgres_user: "tradealert"
  postgres_password: "securepassword"
  redis_password: "redispass"
