server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tradealert
    username: ${DB_USERNAME:tradealert}
    password: ${DB_PASSWORD:change-me}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

rateapis:
  primary-url: ${PRIMARY_RATE_API_URL:https://api.frankfurter.dev/v2/rates}
  secondary-url: ${SECONDARY_RATE_API_URL:https://api.currencyfreaks.com/v2.0/rates/latest}
