spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

smtp:
  host: ${SMTP_HOST:smtp.gmail.com}
  port: ${SMTP_PORT:587}
  user: ${SMTP_USER:uthmanbusayomi@gmail.com}
  pass: ${SMTP_PASS:bfcm jeeh opdr iof}


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      service: verification-service


